### ISSUE TITLE
Output in the shell

### ISSUE THREAD

**Issue by PhoenixAlx** [angrykoala/yamp#101]
Good idea will be able that  by shell to yamp  I put a string in markdown and it will return a output by the shell

```
yamp --html "#example"
```

```
<html>......<h1>example</h1></html>
```

**Comment by angrykoala** [comment]
This will require updating the cli and adding an option for string output.
This issue needs [xejs](https://github.com/angrykoala/xejs) 0.5

**Comment by angrykoala** [comment]
Update, xejs string rendering moved to xejs version 0.6. This issue requires that version
