### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by mmartinsky** [angrykoala/yamp#105]
Failed on npm test immediately following installation. Output attached
[yamp output.txt](https://github.com/angrykoala/yamp/files/530707/yamp.output.txt)

Commands run:

npm install -g yamp
git clone https://github.com/angrykoala/yamp.git
cd yamp
npm install
npm test

**Comment by angrykoala** [comment]
Could you please try and give me the following information:
1. OS and node version
2. Executing `mocha --recursive` works? (this would require you to install mocha globally with `npm install -g mocha`
3. Have you been able to generate a pdf from a md with yamp?
   - If not, try to install _yamp_ globally from npm and check if it works (`npm install -g yamp`)

**Comment by angrykoala** [comment]
Issue close because:
- I was unable to reproduce
- Not enough information given
- Issue reported with an old version of yamp
