### ISSUE TITLE
Highlightjs path is hard code.

### ISSUE THREAD

**Issue by erguotou520** [angrykoala/yamp#127]
In global install case, this works well, but in api mode, `../node_modules/highlight.js/styles/default.css` will not found when dependencies are installed by npm3 or yarn.

**Comment by angrykoala** [comment]
Confirmed, easiest solutions are to store needed files as resources or check both possible paths. Is there a better way?

**Comment by angrykoala** [comment]
Using the minified versions as resources may be a good idea

**Comment by angrykoala** [comment]
This should be fixed in the following minor release 0.4.3
