### ISSUE TITLE
Add --watch option

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#133]

**Comment by nsiregar** [comment]
what is `--watch` option suppose to do?

**Comment by angrykoala** [comment]
It should watch over the origin files (there are several libraries in npm for this) , and when any of them changes, re-compile

**Comment by nsiregar** [comment]
something like nodemon?

**Comment by angrykoala** [comment]
mmm, kinda. personally, I've been using something like `watch -p "*.md" -c "yamp my_file.md"` with the package [watch-cli](https://github.com/doowb/watch-cli), so it would be nice for yamp to integrate this behaviour using --watch

**Comment by nsiregar** [comment]
may i working on this?

**Comment by angrykoala** [comment]
Sure, thanks for your interes
