### ISSUE TITLE
Contributing Guide - Fast Forward issue when push changes

### ISSUE THREAD

**Issue by nsiregar** [angrykoala/yamp#135]
In contributing guide, it is state to use `dev` branch as base branch for PR. But by using this will raise error during `git push` process (non-fast forward problem). Maybe we can use new branch with format like
`
#issuenumber_issue_detail
`
It will make new developer easier to contribute

**Comment by angrykoala** [comment]
Ho @nsiregar , thanks for taking interest in this project.

Please, describe better the problems you are having.

The idea is to use dev as base branch for your PR, but in your own fork you can create any branch you want, and merge, either in your branch or directly with dev in this repo. non-fast forward problems, afaik arise when there are integration problems, these will not be solved by using N different branches, as, in the end, all of them should merge into one (in this case, dev)

I'm not sure if this answers your question

**Comment by nsiregar** [comment]
thank you, this is answer my question

**Comment by angrykoala** [comment]
Then I'll close this issue, thanks for your interest
