### ISSUE TITLE
Code blocks truncated

### ISSUE THREAD

**Issue by psicobyte** [angrykoala/yamp#23]
Code blocks are formatted in HTML using the <pre><code> ... </ code></ pre> tags. If the block is greater than the width of the page, a horizontal scroll bar is displayed (as github pages, off course).

When creating the PDF, this bar is displayed as a static image, it does not allow scrolling text, and the right side is hidden.

This effect is increased because the font in the PDF is too big. With the current font, the code block has a width of 61 characters, apparently.

For example, the following block:

```
text in a code block with many characters:
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```

will create this HTML code:

```
<pre><code> text in a code block with many characters:
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
</code></pre>
```

to display in the PDF as follows:

![captura](https://cloud.githubusercontent.com/assets/1206823/18228239/239daad6-7245-11e6-8045-e3fe7818accb.png)

**Comment by angrykoala** [comment]
This css seems to fix the problem for normal code, but fails when using highlighted code:

``` css
pre code{
white-space: normal;
}
```

![jack](https://cloud.githubusercontent.com/assets/5960567/18228322/b4662a2e-7241-11e6-9dc5-cf825b6688e7.png)

**Comment by angrykoala** [comment]
UPDATE:
code wrap works properly using spaces for new lines, problem appears in long code blocks without space

try a hard word wrap or something like that for pdf output

**Comment by angrykoala** [comment]
This css rule seems to provide the desired behavior for pdf output, there should be different stylesheets or templates for html and pdf output

``` css
pre code{
  white-space: normal;
  word-wrap: break-word;
}
```

**Comment by angrykoala** [comment]
Code block will be hard word-wrapped when the output is a pdf
