### ISSUE TITLE
Comments and documentation

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#38]
Add comments to the code and some documentation (Readme,wiki or groc)

**Comment by ravaan** [comment]
Hey! I was looking at the code, what kind of documentation do you want, text, html..?
Just wanted to know what is required and I will start .

**Comment by angrykoala** [comment]
@ravaan Improving the readme, the files under doc folder. comments based on [groc](https://github.com/nevir/groc) or the github wiki.

Improving any of those would be nice
Thanks

**Comment by angrykoala** [comment]
Upload docs to gh-pages (automatically on npm run docs if possible)
