### ISSUE TITLE
Get input/output files from extension

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#41]
If no option given, use the file extension to check the input and output format

**Comment by tenshi13** [comment]
Good day @angrykoala, may I give this a try?
would like to confirm: 
- file extension would refer to the filename's extension passed in via the -o option?
- what if file extension is .html -> should we then generate html and remarkjs outputs?

tq

**Comment by angrykoala** [comment]
Hi @tenshi13 Of course you can try this

I'm still not sure how the default behavior should be, but in the cli we may have a map between extensions and default renderers.

As you say, this would be used when an output file is specified, but not a renderer (e.g, `yamp test.md -o test.html`)
For html, I would use html renderer by default

this issue is closely related to #102 

thanks, and any question just comment this issue

**Comment by tenshi13** [comment]
Hi @angrykoala ,

I've created a PR https://github.com/angrykoala/yamp/pull/111 for this,
I've refered the comments/example in https://github.com/angrykoala/yamp/issues/102,

please have a review and tell me what you think?

tq

**Comment by angrykoala** [comment]
Requires unit tests (issue #112)
