### ISSUE TITLE
Download external resources on postInstall

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#59]
When installing, download the latest version of all non-npm external resources (reveal, remark etc...).

Maybe add gulp for this process (only if strictly necessary)

**Comment by G07cha** [comment]
Could you please provide full list of required external resources?

**Comment by angrykoala** [comment]
The files under `resources` and under `styles` are potential resources to be downloaded on postInstall. However, I'm still not sure about the best way to do it (or if it would actually improve anything) so this requires some ideas/investigation

**Comment by G07cha** [comment]
I personally think that images and styles could be kept as is and RemarkJS could be installed through bower or directly by Github URL, it really depends on your needs. 

You can just lock current files in the repository if you don't plan to upgrade it. Otherwise, you could pick either sematic update(bower) or direct update(github) which is could be a little bit risky in some cases.

**Comment by angrykoala** [comment]
@G07cha The current remark script is an adapted version of the original remark, so it may be a problem to directly download from the original repositories.

About images and styles, probably you are right

**Comment by G07cha** [comment]
@angrykoala, so what problem are trying to solve then? Reduce repository size?

**Comment by angrykoala** [comment]
The initial idea was to remove the remark script from the repository and provide a mechanism to add and update resources to yamp without changing this repository, but it may not be useful at the current state of the project

**Comment by G07cha** [comment]
If you're using modified version of remark and would like to update it in future you should consider forking original remark repo and maintain it separately. Otherwise, you're right for now it's unnecessary.

**Comment by angrykoala** [comment]
It's just a small change it to be able to embed it into the html. Actually is something a bit messy that I want to get rid of. 

Seems reasonable to close this ticket at wontfix then. thanks @G07cha
