### ISSUE TITLE
Local links in pdf

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#69]
link to a certain page (for example, when TOC is active) fail in PDF

Check if it is possible to make those links to work, if not, disable TOC links on pdf output

**Comment by angrykoala** [comment]
Pdf links doesn't seem feasible. disabling toc links require changes in markdown-toc library. waiting for PR to be accepted https://github.com/jonschlinkert/markdown-toc/pull/73

**Comment by angrykoala** [comment]
PR accepted, update and add those changes

**Comment by erguotou520** [comment]
Currently it seems local link is not work, will be supported?

**Comment by angrykoala** [comment]
No, links will be disabled in pdf using the changes in markdown-toc, unless there is a way to create local links (I've tried but they doesn't seem to be supported by phantom pdfs output)

**Comment by erguotou520** [comment]
Ok, watching for this work.

**Comment by angrykoala** [comment]
Currently, local links in pdf are not supported (probably because of an [html-pdf](https://www.npmjs.com/package/html-pdf) library limitation.
For yamp 0.4.3, the default behaviour will be to disable links in TOC when the output is pdf
