### ISSUE TITLE
Add jshint as part of the CI tests

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#75]
Add an npm script to run jshint (using the rules from .jshintrc) over all the js files.

Add this rule as part of the CI tests

**Comment by sarupbanskota** [comment]
https://github.com/angrykoala/yamp/pull/76.

There are several violations at the moment, though.

**Comment by sarupbanskota** [comment]
This can be closed now?

**Comment by angrykoala** [comment]
@sarupbanskota I'll add jshint as part of npm scripts so it can be also tested offline and fix the js files tht are not passing. This will be close and merged to master soon, thanks
