### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#81]
Create a CHANGELOG.md file (use tool [changelog](https://www.npmjs.com/package/changelog) to begin)

This file should provide all the major versions with main changes and dates

**Comment by nitishkd** [comment]
Hi, I would like to work on this issue.

**Comment by angrykoala** [comment]
Hi, currently the PR #82 added a changelog based on changelog npm module, now the changelog should manually check to remove unesful commit messaged added by the module
