### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#84]
Create a CONTRIBUTING.md file following https://github.com/blog/1184-contributing-guidelines

**Comment by smddzcy** [comment]
I don't know what to write in detail but I've created a general purpose CONTRIBUTING.md file.

**Comment by angrykoala** [comment]
Thanks for your PR @smddzcy, the readme section "Contributors" provides some guidelines that should also be in CONTRIBUTING.md

**Comment by angrykoala** [comment]
@smddzcy do you think the current contributing file requires more changes?
