### ISSUE TITLE
Improve front-matter behavior

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#89]
Front matter options should not override user input options, and it should also support xejs options

the priority should be:
1. user input options
2. front-matter options
3. default renderer options

It is recommended to execute the frontMatter parser somehow within the loader or before loading if possible

**Comment by pv2k** [comment]
I would like to work on this one or any of your issue and I am new to the open source world,please help me with my first PR!! :)

**Comment by angrykoala** [comment]
hi @pv2k I'm glad you want to contribute to this project, please read the [contribution guidelines](https://github.com/angrykoala/yamp/blob/master/CONTRIBUTING.md) of this project and the Pull request info of github(https://help.github.com/articles/about-pull-requests/) to learn about PRs.

You can fork this project and work with your own version until you are happy with the changes and ready to PR. Remember to use the dev branch of this project as base for your PR and work in any issue you want (you can mention issues in you commits and PRs)

**Comment by pv2k** [comment]
thank you @angrykoala
