### ISSUE TITLE
If output option (`-o`) is a folder, parse files in there

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yamp#94]
Currently, the -o option only supports setting a file as output (and will join any input files into one).

If output is a folder, yamp should behave the same way as if there is not an output, but using that folder to create the files.

For example, being docs a folder:

_This command should create 2 files (file1.pdf and file2.pdf) under docs folder_

```
yamp file1.md file2.md -o docs
```

_This command should join the 2 files in one unique file.pdf (as it is now)_

```
yamp file1.md file2.md -o docs/file
```

**Comment by zzarcon** [comment]
Hi! I want to give this a try, will probably open a PR within 1 or 2 days, hope its fine :)

**Comment by angrykoala** [comment]
@zzarcon I would like to add this issue to release 0.4
Are you actively working on this?

**Comment by daanvanham** [comment]
Sorry, PR was too soon. The first command where two files should be written is not yet working. Files are always written as one.

**Comment by daanvanham** [comment]
Updated PR with the fix

**Comment by angrykoala** [comment]
This seems to be working fine, require some unit testing to ensure correct behavior of renderer class
